# -*- coding: utf-8 -*-
"""Lab-1-2026.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kxroixJj66T8CDsgzsnPmvMbVHkUfwx5

#Lab 1: Introduction to ScikitLearn, Preprocessing and Classification Tasks

During this Lab, we aim to achieve the following:


*   Get familiar with <a href="https://scikit-learn.org/stable/"> scikit-learn </a>, an essential python library in data science;
*   Get familiar with text preprocessing
*   learn how to approach a text classification task with scikit-learn.

In this notebook, we learn to use Scikit-Learn with a practical example and then, in the second part, we will test our knowledge by doing some exercises.

#Exercise 1: Zipf Law

I collected texts by Agatha Christie from the Gutenberg project:

  1. https://www.math.unipd.it/~dasan/christie.txt

You need to write a code to show to what extent those texts follow the Zipf law. The law states that, if we sort the words according to their frequency (from most to least frequent), the normalised frequency of the N-th word in a text roughly follows this rule $$\frac{1}{(N+b)^a}$$

for some parameters a,b.

We have seen the resulting plot in the first class of the course. See [this link for a short description.](https://phys.org/news/2017-08-unzipping-zipf-law-solution-century-old.html) of the Zipf law.

You are already given some snippets of code that allow you to:
  1. collect the texts given the url. In case the website is slow due to high traffic, while you are building the code you can test it on a small string you can extract from the text or create yourself.
  2. sort the dictionary of values according to the frequencies
  3. plot the word frequencies
  4. print the information to be copied on the Moodle when submitting your exercise.

You need to complete the code that preprocess the data and results in a dictionary whose keys are words and values their frequencies. You need to pay attention to what to consider as word (what do you compute frequency of). There are clearly some items that should be discarded because they are not words. Other preprocessing choices could make sense either way.

You can verify the Zipf law for the following texts as well:

  1. https://www.math.unipd.it/~dasan/shakespeare.txt
  2. https://www.math.unipd.it/~dasan/twain.txt
  3. https://www.math.unipd.it/~dasan/verne.txt

 This last part is not part of the lab-exercises, but we can discuss the results in class. Beware that the files are much larger, so do not run the code while in the lab. It is best to download the files once and modify the code to work locally.
"""

import numpy as np
import scipy.optimize as opt
import matplotlib.pyplot as plt
import sys
import requests
import string


def plot(freq, author, limit=-1):
  """
    freq: a list of ordered frequency values
    author: a string representing the author of the texts
    limit: how many words are being plotted
  """
  def func(x, a, b):
    return 1/((x+b) * np.exp(a))

  rank = list(range(1, len(freq)+1))
  maxf = max(freq)
  freq = [f/maxf for f in freq] #normalized frequencies w.r.t. the maximum frequence

  #Plot the rank and frequency
  plt.plot(rank[:limit], freq[:limit], label=author)

  # Labelling the x axis
  plt.xlabel('Word Rank')
  # Labelling the y axis
  plt.ylabel('Frequency')

  bestparams, p = opt.curve_fit(func, rank, freq)
  plt.plot(rank[:limit], func(rank[:limit], *bestparams), label="fit")
  plt.text(limit-100, 0.15, "a=%.3f\nb=%.3f"%(bestparams[0], bestparams[1]))

  # Providing a title to the graph
  plt.title("Zipf's law")

  plt.legend()
  plt.show()
  return bestparams[0], bestparams[1]

import numpy as np
import scipy.optimize as opt
import matplotlib.pyplot as plt
import sys
import requests
import string


input_file = "https://www.math.unipd.it/~dasan/christie.txt"


data = requests.get(input_file).text  # get the text from the url, data is a string
textDict = {} # the keys of the dictionary will be words, the values their frequencies


#### Add your code here to fill textDict
import nltk
from nltk import word_tokenize
from nltk.stem import PorterStemmer, WordNetLemmatizer, SnowballStemmer
from nltk.corpus import stopwords
from nltk import FreqDist
import re
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('wordnet')

token_list = word_tokenize(data) #create the list of tokens
print(f'The len of the list of token is{len(token_list)}')
print(token_list[:55])

token_list = [token.lower() for token in token_list] #lower all the words
print(token_list[:55])

token_no_punct = [re.sub(r'[^\w\s-]', '', token) for token in token_list] #remove all the punctuation and replace it with ''
token_clean = [token for token in token_no_punct if token] #removing the ''
print(f'The len of the list of token with no punctuation is{len(token_clean)}')
print(token_clean[:55])

#Stemming
porter = PorterStemmer()
snow_stemmed_token=[porter.stem(token) for token in token_clean] #stemming
print(f'The len of the list of token with no punctuation and stemmed is {len(snow_stemmed_token)}')
print(snow_stemmed_token[:55])
#The stemming presents its usual errors given by how the words are cut, for example the word 'was' was cut in 'wa'

textDict = dict(FreqDist(snow_stemmed_token))
print(f'In the end we count {len(textDict)} tokens')


####

textDict = dict(sorted(textDict.items(), key=lambda item: item[1], reverse=True)) # sort the words by frequency

a,b = plot(textDict.values(), "Christie", 150)

##### Copy all the text that is printed from the following commands in Moodle
print("number of items = ", len(textDict))
for i,t in enumerate(list(textDict.keys())[:25]):
  print(i, t, textDict[t])
print ("a=", a, "b=", b)

"""## Lab Assignment

Copy the output generated by the instructions below "##### Copy all the text that is printed from the following commands in Moodle" in the text box of the assignment on Moodle

#Sentiment Analysis

The dataset is described here: https://www.aclweb.org/anthology/P04-1035.pdf

It is part of nltk, so it is convenient for us to use.

The goal of this exercise is to build a first machine learning model using the tools that we have seen so far: choose how to preprocess the text, create a bag of words feature representation, train a model using an ML method of your choice.

You need to use the following split for the data:

*   test: 30% of the documents
*   The rest of the documents will be split as
    *   train: 75% of the documents
    *   validation: 25% of the documents


Use accuracy as evaluation measure.
"""

import nltk
nltk.download('movie_reviews') # loads the dataset
nltk.download('punkt')
!python -m spacy download "en_core_web_sm"

"""## Loading the data
In the following I extract the raw content of the reviews (movie_reviews.raw()), i.e. each review is a string.
Another option is to use movie_reviews.words() that returns each review as a list of tokens. Feel free to use whichever best fit your needs.

"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets
from nltk.corpus import movie_reviews
import random
import spacy
from scipy.sparse import coo_matrix, vstack
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
import pandas as pd
import random


nlp_en = spacy.load("en_core_web_sm", disable=['ner', 'parser'])

documents = [(movie_reviews.raw(fileid), category)
              for category in movie_reviews.categories()
              for fileid in movie_reviews.fileids(category)]

print("number of docs loaded:", len(documents))

corpus_raw = [ x[0] for x in documents ]  # corpus_raw is a list of strings (reviews) to be converted into vectors
y_corpus = [ x[1] for x in documents ]    # y_corpus are the sentiment labels of the reviews (nothing to be done here)

# printing an example document and its class
print(corpus_raw[0])  # notice the noise in the review (especially the last row)
print(y_corpus[0])    # the class is "neg", but scikit learn is able to handle non numerical labels automatically

random.seed(42)

"""## Exercise 2

Create a vectorial representation of the data, then apply a learning algorithm by optimising the hyperparameters on the dev set. If you need to use any function that depends on random number generators, use 42 as seed.
Once you have selected the hyperparameters and the preprocessing, retrain your model on the union of the training and validation sets, then compute the accuracy on the test set.

Report your test performance on Moodle.

**"Bonus Exercise"** for your best model, print the 30 tokens whose corresponding parameter have highest absolute value. What do you think of this list? Does it make sense? Are all tokens expected?

"""

#splitting the raw corpus

from sklearn.model_selection import train_test_split, KFold

data_tr, data_test, y_tr, y_test = train_test_split(corpus_raw, y_corpus, random_state=42, test_size=0.3)
print(len(data_tr))
print(len(data_test))
print(len(y_tr))
print(len(y_test))

#definition of the custom tokenizer to use

from nltk import word_tokenize
from nltk.corpus import stopwords
nltk.download("stopwords")
nltk.download('punkt_tab')
nltk.download('wordnet')


en_stopwords = set(stopwords.words('english')) # Pre-load stopwords into a set for multiprocessing safety

def custom_tokenizer(text):
  tokens = word_tokenize(text) #lower the text
  token_no_punct = [token for token in tokens if token.isalpha()] #remove the tokens containing punctuation
  token_clean = [token for token in token_no_punct if token not in en_stopwords] #remove the stopwords
  return token_clean

prova = custom_tokenizer(data_tr[0])
print(prova)

#definition of the vectorizer

vec = CountVectorizer(binary = True, tokenizer = custom_tokenizer, ngram_range = (1,3))

from sklearn.pipeline import Pipeline

pipe = Pipeline([
    ('vectorizer', vec), ('classifier', None)
])

#grid of parameters and models to try out

from sklearn.svm import SVC

param_grid = [
    {'classifier' : [LogisticRegression()], 'classifier__C' : [0.001, 0.01, 0.1, 1.0]},
    {'classifier' : [SVC()], 'classifier__kernel' : ['linear', 'rbf'], 'classifier__C' : [0.001, 0.01, 0.1, 1.0]}
]

from sklearn.model_selection import GridSearchCV

grid_search = GridSearchCV(
    estimator = pipe,
    param_grid = param_grid,
    cv = 4,
    scoring = 'accuracy',
    n_jobs = -1
    )

#TRAINING

grid_search.fit(data_tr, y_tr)

#printing the accuracy for each model, to see the best

results = pd.DataFrame(grid_search.cv_results_)
print(results.columns)
print(results.loc[:, ['param_classifier', 'param_classifier__C', 'mean_test_score', 'rank_test_score']])

#check the performance on the test set
model = grid_search.best_estimator_

predictions = model.predict(data_test)

accuracy_score(y_test, predictions)

vectorizer = model.named_steps['vectorizer']
classifier = model.named_steps['classifier']

features_name = np.array(vectorizer.get_feature_names_out()) #the tokens
coefficient = classifier.coef_[0] #the weight of each token

abs_coef = np.abs(coefficient)

top_30_indices = np.argsort(abs_coef)[-30:][::-1]

top_30_tokens = features_name[top_30_indices]
top_30_weights = coefficient[top_30_indices]

print(f'{'Token':<15} | {'Weight':<10} | Impact')
print('*'*50)
for token, weight in zip(top_30_tokens, top_30_weights):
  impact = "Positive (+)" if weight > 0 else "Negative (-)"
  print(f'{token:<15} | {weight:<10.4f} | {impact}')

"""Now we define the pipeline and the combinations of models we want to try out

# at least 0.82 accuracy

## for Ex1
look at the first $25$ word and see if there is something weird there

#Submission of the Lab exercises

In Moodle you are supposed to upload the notebook in .py format (Menu File->Download->Download .py)
Comment your code nd motivate any significant choice you have made. It is ok to show all the attempts you made as commented code, but make sure that, when running the code, only your best attempt is exectued.

In addition each exercise asks to copy on Moodle, in the text box of your submission, some outputs of your code. These are critical to evaluate your exercises.
"""